package com.care.appointment.web.dto.reports;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import java.util.List;

/**
 * Response DTO for Excel Report Generation
 * Returns file information and optionally preview data
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@Schema(description = "Response for Excel report generation")
public class ExcelReportResponse {

    @Schema(description = "Report type that was generated")
    private String reportType;

    @Schema(description = "File name of generated report")
    private String fileName;

    @Schema(description = "File content as base64 encoded string")
    private String fileContent;

    @Schema(description = "File size in bytes")
    private long fileSize;

    @Schema(description = "Report generation timestamp")
    private String generatedAt;

    @Schema(description = "Preview data (optional, depends on report type)")
    private Object previewData;

    @Schema(description = "Summary statistics")
    private ReportSummary summary;

    /**
     * Report Summary DTO
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @ToString
    @Schema(description = "Report summary")
    public static class ReportSummary {
        @Schema(description = "Total records in report")
        private long totalRecords;

        @Schema(description = "Report period from date")
        private String periodFrom;

        @Schema(description = "Report period to date")
        private String periodTo;

        @Schema(description = "Applied filters description")
        private String appliedFilters;

        @Schema(description = "Generated by user ID")
        private String generatedBy;
    }
}
